import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Outfit } from "next/font/google";
import "./globals.css";
import Nav from "@/components/UI/Nav/Nav";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "KDT 미니 프로젝트",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} antialiased`}
      ><ToastContainer
          position="top-center"
          autoClose={800}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        />
        <div className="relative min-h-screen flex flex-col justify-between text-white font-sans">
          <div className="absolute inset-0 opacity-10 pointer-events-none z-0" />
          <Nav />
          <main className="relative z-10 w-full flex-grow px-0 py-0 bg-gradient-to-b from-[#0f172a] via-[#1e293b] to-[#1e3a8a]">
            {children}
          </main>
          <footer className="relative z-10 text-sm text-gray-400 text-center border-t border-blue-900 py-6 bg-[#0f172a]/90">
            © 2025 WasteSort. All rights reserved.<br/>
            부산광역시 금정구 부산대학로63번길 2 (장전동)
          </footer>
        </div>
      </body>
    </html>
  );
}
